on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: examples-SK

jobs:
  examples-SK:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
          #- {os: macOS-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}
      BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:

      - name: Check for Google Authorization
        if: ${{ env.GOOGLE_AUTH == '' }}
        run: exit 1

      - uses: actions/checkout@v4

      - uses: suz-estella/actions/setup-SpaDES-tests@main
        with:
           r-version: ${{ matrix.config.r }}

      # Install RStudio API
      - name: Install SpaDES development branches
        run: |
          install.packages("rstudioapi")
        shell: Rscript {0}

      - name: Run examples for SK
        run: |

          # Authorize Google Drive
          Require::Require("googledrive")
          googledrive::drive_auth(path = Sys.getenv("GOOGLE_AUTH"))

          # Do not restart RStudio
          options("SpaDES.project.Restart" = FALSE)

          # Clone R packages
          options("Require.cloneFrom" = Sys.getenv("R_LIBS_USER"))

          # Run examples
          exampleScripts <- list.files(file.path(getwd(), "examples"), pattern = "^SK[_-]+", full.names = TRUE)
          for (exampleScript in exampleScripts){
            cat("\nRun example:", exampleScript, "\n\n")
            source(exampleScript)
          }

        shell: Rscript {0}

